### ISSUE TITLE
IllegalArgumentException at LoginManager.jsp (line 40)

### ISSUE THREAD

**Issue by Zakusov** [idega/com.idega.manager#1]
To reproduce:
1. download com.idega.app.eplatform.win32-4.1.3-20091126.212618-4.zip from http://idega.org/gettingstarted.html
2. unzip it
3. start idega.exe 
4. login as Administrator/idega
5. click Manager -> Install & Update
--> Exception:

javax.faces.FacesException: An exception occurred processing JSP page /idegaweb/bundles/com.idega.manager.bundle/jsp/LoginManager.jsp at line 40

37:                         styleClass="managerLogin"
38:                         binding="#{LoginManager.outputText3}" 
39:                         id="outputText3" 
40:                         value="#{LoginManager.outputText3Value}"/>
41:                     <h:inputText binding="#{LoginManager.textField1}" 
42:                         style="width: 300px"
43:                         id="textField1"/>

Stacktrace:
    at org.apache.myfaces.context.servlet.ServletExternalContextImpl.dispatch(ServletExternalContextImpl.java:347)
    at org.apache.myfaces.application.jsp.JspViewHandlerImpl.buildView(JspViewHandlerImpl.java:486)
    at org.apache.myfaces.application.jsp.JspViewHandlerImpl.renderView(JspViewHandlerImpl.java:337)
    at com.idega.faces.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:96)
    at com.idega.faces.IWJspViewHandler.renderView(IWJspViewHandler.java:101)
    at com.idega.faces.IWViewHandlerImpl.renderView(IWViewHandlerImpl.java:270)
    at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:41)
    at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:140)
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:155)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.myfaces.webapp.filter.ExtensionsFilter.doFilter(ExtensionsFilter.java:285)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at is.idega.idegaweb.egov.bpm.servlet.CommentViewerRedirector.doFilter(CommentViewerRedirector.java:50)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at is.idega.idegaweb.egov.bpm.servlet.TaskViewerRedirector.doFilter(TaskViewerRedirector.java:45)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at is.idega.idegaweb.egov.application.servlet.filter.ApplicationUrlRedirector.doFilter(ApplicationUrlRedirector.java:71)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at com.idega.slide.authentication.IWSlideAuthenticator.doAuthentication(IWSlideAuthenticator.java:181)
    at com.idega.slide.authentication.IWSlideAuthenticator.doFilter(IWSlideAuthenticator.java:76)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at com.idega.servlet.filter.GZIPFilter.doFilter(GZIPFilter.java:86)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.myfaces.webapp.filter.ExtensionsFilter.doFilter(ExtensionsFilter.java:341)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at com.idega.servlet.filter.IWAuthorizationFilter.doFilter(IWAuthorizationFilter.java:111)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at com.idega.servlet.filter.IWWelcomeFilter.doFilter(IWWelcomeFilter.java:126)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at com.idega.servlet.filter.IWAuthenticator.doFilter(IWAuthenticator.java:184)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at com.idega.servlet.filter.IWUrlRedirector.doFilter(IWUrlRedirector.java:72)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at com.idega.servlet.filter.IWEncodingFilter.doFilter(IWEncodingFilter.java:58)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:567)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:849)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:583)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:454)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.jasper.JasperException: An exception occurred processing JSP page /idegaweb/bundles/com.idega.manager.bundle/jsp/LoginManager.jsp at line 40

37:                         styleClass="managerLogin"
38:                         binding="#{LoginManager.outputText3}" 
39:                         id="outputText3" 
40:                         value="#{LoginManager.outputText3Value}"/>
41:                     <h:inputText binding="#{LoginManager.textField1}" 
42:                         style="width: 300px"
43:                         id="textField1"/>

Stacktrace:
    at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:505)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:416)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:342)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:267)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:646)
    at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:436)
    at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:374)
    at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:302)
    at org.apache.myfaces.context.servlet.ServletExternalContextImpl.dispatch(ServletExternalContextImpl.java:341)
    ... 58 more
Caused by: java.lang.IllegalArgumentException: Component javax.faces.component.html.HtmlOutputText is no javax.faces.component.html.HtmlOutputLabel
    at org.apache.myfaces.taglib.html.HtmlOutputLabelTag.setProperties(HtmlOutputLabelTag.java:196)
    at javax.faces.webapp.UIComponentELTag.createComponent(UIComponentELTag.java:103)
    at javax.faces.webapp.UIComponentClassicTagBase.findComponent(UIComponentClassicTagBase.java:1104)
    at javax.faces.webapp.UIComponentClassicTagBase.doStartTag(UIComponentClassicTagBase.java:434)
    at org.apache.jsp.idegaweb.bundles.com_idega_manager_bundle.jsp.LoginManager_jsp._jspx_meth_h_005foutputLabel_005f0(LoginManager_jsp.java:578)
    at org.apache.jsp.idegaweb.bundles.com_idega_manager_bundle.jsp.LoginManager_jsp._jspx_meth_wf_005fcontainer_005f3(LoginManager_jsp.java:536)
    at org.apache.jsp.idegaweb.bundles.com_idega_manager_bundle.jsp.LoginManager_jsp._jspx_meth_wf_005fwfblock_005f0(LoginManager_jsp.java:255)
    at org.apache.jsp.idegaweb.bundles.com_idega_manager_bundle.jsp.LoginManager_jsp._jspx_meth_h_005fform_005f0(LoginManager_jsp.java:211)
    at org.apache.jsp.idegaweb.bundles.com_idega_manager_bundle.jsp.LoginManager_jsp._jspx_meth_ws_005fpage_005f0(LoginManager_jsp.java:171)
    at org.apache.jsp.idegaweb.bundles.com_idega_manager_bundle.jsp.LoginManager_jsp._jspx_meth_f_005fview_005f0(LoginManager_jsp.java:131)
    at org.apache.jsp.idegaweb.bundles.com_idega_manager_bundle.jsp.LoginManager_jsp._jspService(LoginManager_jsp.java:99)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:374)
    ... 68 more

**Comment by bluebottle** [comment]
The windows build is over a year old and no one is maintaining it. Think I will probably just delete it.

**Comment by sputnick** [comment]
In other words the "manager" is depricated and nonexistent.

**Comment by Zakusov** [comment]
So how can I get the latest version of Idega? Only via building from source?

REM: I need just a war. As I understood I can build it from git://github.com/idega/idega-webapp-base.git. Isn't it?

**Comment by Zakusov** [comment]
sputnick, what do you mean "manager is depricated and nonexistent"?
I've got the latest version of Idega sources, built it and when I try to Install/Update modules I see that there is used com.idega.manager code - see https://github.com/idega/com.idega.manager/issues/2
